### ISSUE TITLE
Installed but curl commands seem to have no effect

### ISSUE THREAD

**Issue by midfm** [Jean-Tinland/simple-bar-server#1]
Hi Jean,

Thanks for Simpe-Bar and for this new capability too - the idea of controlling the widgets this way is great. Unfortunately I haven't been able to make it work. I attempted to follow your install instructions, and reviewed them several times. This may well be a configuration problem, not a bug - apologies if that turns out to be the case!

I have checked:

- Dependencies -- npm and pm2 -- are ahead of the required versions. 
- Signals are added to .yabairc (port in the signals matches the http port in the config.json file) - I used your examples from README.md. Confirmed they are listed in the output of `yabai -m signal --list`.
- Confirmed that node has macOS automation permissions to control Ubersicht.
- Logs from pm2: "simple-bar-server-out.log" just show that simple-bar-server is running on localhost with the expected port (again, the http port from the config.json file). "simple-bar-server-error.log" just has a warning that "Importing JSON modules is an experimental feature" 
- In simple-bar settings ("server socket port"), the port matches the http port in the config.json file

When I enable the two check boxes in the simple-bar settings, the space indicator and active apps no longer update.

Manually running the curl commands, in a terminal, has no effect either, though running curl `-v`, the request does get a 200 response (with no visible effect on simple-bar) :
```
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Fri, 01 Mar 2024 23:04:31 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
<
* Connection #0 to host 127.0.0.1 left intact
```

The only feedback I can see that seems to indicate a problem is in the Ubersich web inspector foreground debug console:
```
[Error] WebSocket connection to 'ws://localhost:7776/?target=windows' failed: There was a bad response from the server.
[Error] WebSocket connection to 'ws://localhost:7776/?target=user-widget&userWidgetIndex=1' failed: There was a bad response from the server.
[Error] WebSocket connection to 'ws://localhost:7776/?target=wifi' failed: There was a bad response from the server.
```
Do you have any tips for me, please? I could well be missing something obvious.

**Comment by Jean-Tinland** [comment]
Hi! Thank you for your message, I'm glad these tools are useful for you!

Also thank you for the detailed issue, I think you made almost everything correctly.

At first glance I'm not sure the port used for the web socket is the right one. By default it should be `7777` (ws) in simple-bar settings.

```json
{
  "ports": {
    "http": 7776,
    "ws": 7777
  }
}
```

<img width="364" alt="image" src="https://github.com/Jean-Tinland/simple-bar-server/assets/43068795/f6ac864f-33e9-437c-8344-77fca3fcb1bb">

In your case it seems that simple-bar attempts to connect its sockets to the http server, not the web socket one.

The `7776` port is for the http server that should receive the `curl` requests.

Let me know if this solves your issue. If so I'll try to improve the documentation to make this more obvious as it is a bit confusing right now :)

**Comment by midfm** [comment]
Yes, that was it!

Curl commands are now working, and in simple-bar itself I'm able see the effects - refreshing and activating/deactivating widgets.

 Thank you very much - kicking myself for not figuring that out (or even just trying it). Closing this issue.

(edited to remove reference to another issue, that has been posted [here](https://github.com/Jean-Tinland/simple-bar-server/issues/2) - moving my own comment to that issue).
