### ISSUE TITLE
Processes widget disappear when activate "refresh space & process with simple-bar-server" (SIP disabled)

### ISSUE THREAD

**Issue by minhttx** [Jean-Tinland/simple-bar-server#2]
I'm using simple-bar with simple-bar-server, ws 7777, http 7776, already add signals to yabairc.
Before disable SIP, everything was ok. process widget displayed fine when activate "refresh space & process with simple-bar-server".
After disable SIP, it disappears, only briefly appear when the bar start and then vanish. However, when deactivate "refresh space & process with simple-bar-server", it works again.
What can I do now?

**Comment by midfm** [comment]
I'm having the same issue.

Space changes do update the active space indicator, but the active apps are not visible (no App icons within the space indicators) nor are current process / window title, or the current space mode indicator.

The problem seems to be corrected when I Refresh All Widgets via Ubersicht in the  Menu Bar, but as soon as I focus an application window, all Process related info disappears from simple-bar.

As described by @minhttx, everything works fine if I don't have "Refresh spaces & process with simple-bar-server" checked. 

I have very recently updated to Yabai v6.0.15, but since I didn't have this working before, I can't tell whether that has made any difference.

Looking in the debug console, I see error:

 `SyntaxError: JSON Parse error: Expected '}' — utils.js:6`

...followed by the JSON output from a Yabai command (looks like it's from `yabai -m query --windows`?). And this is repeated seemingly every time some of the signals are fired.  I see that `utils.js` (and I guess `yabai.js`?) is part of simple-bar, not simple-bar-server though. 

Thanks!

**Comment by Jean-Tinland** [comment]
I already encountered similar issue with he output of this command: `yabai -m query --windows`. I'm patching the output in order to make it parsable by `JSON.parse()`. It is possible that some characters in the json output of the command are not patched yet in my implementation.

Do you think you could share here the output of this command only if you don't have any sensitive information in it? It would help me a lot fixing this. 

You can try to close every opened app and reopen them one by one until it is crashing again. Then run `yabai -m query --windows` and paste the output here.

Otherwise you can try to debug it locally by running a small node script doing the following:

```javascript
// Create an index.js file and run it with: node index.js

const output = "paste here the result of the yabai command";

const patchedOutput = output.replace(/\.|\\n/g, "").replace(/00000/g, "0");

console.log(JSON.parse(patchedOutput));
```

This is what `simple-bar` is doing when synced with `simple-bar-server`.

If an error is happening, you can try to `console.log(patchedOutput)` and paste the patched output into a json linter like https://jsonlint.com/ and see what line is causing the error.

Let me know if any of this helps you.

**Comment by minhttx** [comment]
hi. the output is as below:

[{
	"id":4824,
	"pid":57241,
	"app":"Alacritty",
	"title":"Alacritty",
	"frame":{
		"x":1289.0000,
		"y":532.0000,
		"w":609.0000,
		"h":492.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":2,
	"level":0,
	"sub-level":-20,
	"layer":"normal",
	"sub-layer":"below",
	"opacity":1.0000,
	"split-type":"vertical",
	"split-child":"second_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":true,
	"has-shadow":false,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":305,
	"pid":11799,
	"app":"Telegram",
	"title":"Telegram",
	"frame":{
		"x":660.0000,
		"y":532.0000,
		"w":609.0000,
		"h":550.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":2,
	"level":0,
	"sub-level":-20,
	"layer":"normal",
	"sub-layer":"below",
	"opacity":0.9000,
	"split-type":"vertical",
	"split-child":"first_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":false,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":78,
	"pid":670,
	"app":"Messenger",
	"title":"Messenger",
	"frame":{
		"x":660.0000,
		"y":20.0000,
		"w":1239.0000,
		"h":500.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":2,
	"level":0,
	"sub-level":-20,
	"layer":"normal",
	"sub-layer":"below",
	"opacity":0.9000,
	"split-type":"horizontal",
	"split-child":"first_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":false,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":3804,
	"pid":85454,
	"app":"Zalo",
	"title":"Zalo",
	"frame":{
		"x":20.0000,
		"y":20.0000,
		"w":620.0000,
		"h":1004.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":2,
	"level":0,
	"sub-level":-20,
	"layer":"normal",
	"sub-layer":"below",
	"opacity":0.9000,
	"split-type":"vertical",
	"split-child":"first_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":false,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":4323,
	"pid":22403,
	"app":"Safari",
	"title":"$63748.58 BTC USDT Giá Hợp Đồng Vĩnh Viễn Tuyến Tính | Phái Sinh Bitcoin | Giao Dịch Ký Quỹ Hợp Đồng BingX",
	"frame":{
		"x":-1420.0000,
		"y":534.0000,
		"w":1400.0000,
		"h":824.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":2,
	"space":4,
	"level":0,
	"sub-level":-20,
	"layer":"normal",
	"sub-layer":"below",
	"opacity":1.0000,
	"split-type":"none",
	"split-child":"second_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":false,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":1815,
	"pid":2430,
	"app":"Arc",
	"title":"Processes widget disappear when activate \"refresh space & process with simple-bar-server\" (SIP disabled) · Issue #2 · Jean-Tinland/simple-bar-server",
	"frame":{
		"x":20.0000,
		"y":20.0000,
		"w":1880.0000,
		"h":1004.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":1,
	"level":0,
	"sub-level":-20,
	"layer":"normal",
	"sub-layer":"below",
	"opacity":1.0000,
	"split-type":"none",
	"split-child":"second_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":false,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":false,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":4265,
	"pid":89646,
	"app":"Microsoft Word",
	"title":"Nguyen An - Thanh Quang.docx",
	"frame":{
		"x":970.0000,
		"y":20.0000,
		"w":930.0000,
		"h":1004.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":3,
	"level":0,
	"sub-level":-20,
	"layer":"normal",
	"sub-layer":"below",
	"opacity":1.0000,
	"split-type":"vertical",
	"split-child":"second_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":false,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":false,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":4218,
	"pid":89646,
	"app":"Microsoft Word",
	"title":"XM-Ai-Info.docx",
	"frame":{
		"x":20.0000,
		"y":20.0000,
		"w":930.0000,
		"h":1004.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":3,
	"level":0,
	"sub-level":-20,
	"layer":"normal",
	"sub-layer":"below",
	"opacity":0.9000,
	"split-type":"vertical",
	"split-child":"first_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":false,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":false,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":3540,
	"pid":85259,
	"app":"Obsidian",
	"title":"Anh (chị) hãy cho biết mục đích của việc thuyết trình theo nhóm? - Documents - Obsidian v1.5.8",
	"frame":{
		"x":1230.0000,
		"y":20.0000,
		"w":609.0000,
		"h":1004.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":1,
	"level":0,
	"sub-level":0,
	"layer":"normal",
	"sub-layer":"normal",
	"opacity":0.9000,
	"split-type":"none",
	"split-child":"none",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":false,
	"is-minimized":true,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":4259,
	"pid":505,
	"app":"Finder",
	"title":"/Volumes/CS/XM",
	"frame":{
		"x":940.0000,
		"y":20.0000,
		"w":900.0000,
		"h":1004.0000
	},
	"role":"AXWindow",
	"subrole":"AXDialog",
	"root-window":true,
	"display":1,
	"space":3,
	"level":0,
	"sub-level":0,
	"layer":"normal",
	"sub-layer":"normal",
	"opacity":0.9000,
	"split-type":"none",
	"split-child":"none",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":false,
	"is-minimized":true,
	"is-hidden":false,
	"is-floating":true,
	"is-sticky":false,
	"is-grabbed":false
}]

**Comment by Jean-Tinland** [comment]
Thanks! This is weird, it seems that double quotes `"` are not escaped by `yabai` on your end. 

On my machine, the window titles containing `"` are correctly escaped: `"title":"Processes widget disappear when activate \"refresh space & process with simple-bar-server\" (SIP disabled) · Issue #2 · Jean-Tinland/simple-bar-server",`.

What version of `yabai` are you using? It seems to be an issue identified [here](https://github.com/koekeishiya/yabai/issues/114) fixed since.

**Comment by minhttx** [comment]
> Thanks! This is weird, it seems that double quotes `"` are not escaped by `yabai` on your end.
> 
> On my machine, the window titles containing `"` are correctly escaped: `"title":"Processes widget disappear when activate \"refresh space & process with simple-bar-server\" (SIP disabled) · Issue #2 · Jean-Tinland/simple-bar-server",`.
> 
> What version of `yabai` are you using? It seems to be an issue identified [here](https://github.com/koekeishiya/yabai/issues/114) fixed since.

i'm using yabai-v6.0.15, macos sonoma, simple-bar and simple-bar-server latest.

**Comment by Jean-Tinland** [comment]
I see, I was mistaken, it is simply github.com that removes the escaping characters in plain text. This output seems to be valid. It must be something else, I will keep digging and keep you posted!

**Comment by minhttx** [comment]
> I see, I was mistaken, it is simply github.com that removes the escaping characters in plain text. This output seems to be valid. It must be something else, I will keep digging and keep you posted!

thanks. Rightnow i'm using simple-bar-server for widget refreshing, and ubersicht for space & process widget. I notice a little bit lag, but at least it's working while a solution is found.

**Comment by AcerLaze** [comment]
Hello, I did some digging and found out it seems the issue is on the simple-bar.
Specifically on this line :
https://github.com/Jean-Tinland/simple-bar/blob/3a9302d8d980b9330077a01e2aa2c7d3d43c63ed/lib/yabai.js#L45

This will replace all "." occurrence and when trying to convert value like 0.9000, because it will be replaced as 09000 which  will cause parsing error.

Currently my temp fix is just simply remove that line of code.

**Comment by AcerLaze** [comment]
Hello, I've encountered similar issue and did some digging and found out when cleaning json it doesn't take in account if the there is a value like 0.9500.
https://github.com/Jean-Tinland/simple-bar/blob/3a9302d8d980b9330077a01e2aa2c7d3d43c63ed/lib/yabai.js#L45

This is the cleaned json in the debug log :
```
"[{
	\"id\":40262,
	\"pid\":24006,
	\"app\":\"Firefox\",
	\"title\":\"Processes widget disappear when activate \\\"refresh space & process with simple-bar-server\\\" (SIP disabled) · Issue #2 · Jean-Tinland/simple-bar-server\",
	\"frame\":{
		\"x\":50000,
		\"y\":40,
		\"w\":1430,
		\"h\":8550000
	},
	\"role\":\"AXWindow\",
	\"subrole\":\"AXStandardWindow\",
	\"root-window\":true,
	\"display\":1,
	\"space\":3,
	\"level\":0,
	\"sub-level\":-20,
	\"layer\":\"normal\",
	\"sub-layer\":\"below\",
	\"opacity\":09615,
	\"split-type\":\"none\",
	\"split-child\":\"second_child\",
	\"stack-index\":0,
	\"can-move\":true,
	\"can-resize\":true,
	\"has-focus\":true,
	\"has-shadow\":true,
	\"has-parent-zoom\":false,
	\"has-fullscreen-zoom\":false,
	\"is-native-fullscreen\":false,
	\"is-visible\":true,
	\"is-minimized\":false,
	\"is-hidden\":false,
	\"is-floating\":false,
	\"is-sticky\":false,
	\"is-grabbed\":false
}]
"
```
`opacity` before cleaned was 0.9615 but after cleaned, it converted into 09615 which causes an error when parsing

**Comment by minhttx** [comment]
> Hello, I've encountered similar issue and did some digging and found out when cleaning json it doesn't take in account if the there is a value like 0.9500. https://github.com/Jean-Tinland/simple-bar/blob/3a9302d8d980b9330077a01e2aa2c7d3d43c63ed/lib/yabai.js#L45
> 
> This is the cleaned json in the debug log :
> 
> ```
> "[{
> 	\"id\":40262,
> 	\"pid\":24006,
> 	\"app\":\"Firefox\",
> 	\"title\":\"Processes widget disappear when activate \\\"refresh space & process with simple-bar-server\\\" (SIP disabled) · Issue #2 · Jean-Tinland/simple-bar-server\",
> 	\"frame\":{
> 		\"x\":50000,
> 		\"y\":40,
> 		\"w\":1430,
> 		\"h\":8550000
> 	},
> 	\"role\":\"AXWindow\",
> 	\"subrole\":\"AXStandardWindow\",
> 	\"root-window\":true,
> 	\"display\":1,
> 	\"space\":3,
> 	\"level\":0,
> 	\"sub-level\":-20,
> 	\"layer\":\"normal\",
> 	\"sub-layer\":\"below\",
> 	\"opacity\":09615,
> 	\"split-type\":\"none\",
> 	\"split-child\":\"second_child\",
> 	\"stack-index\":0,
> 	\"can-move\":true,
> 	\"can-resize\":true,
> 	\"has-focus\":true,
> 	\"has-shadow\":true,
> 	\"has-parent-zoom\":false,
> 	\"has-fullscreen-zoom\":false,
> 	\"is-native-fullscreen\":false,
> 	\"is-visible\":true,
> 	\"is-minimized\":false,
> 	\"is-hidden\":false,
> 	\"is-floating\":false,
> 	\"is-sticky\":false,
> 	\"is-grabbed\":false
> }]
> "
> ```
> 
> `opacity` before cleaned was 0.9615 but after cleaned, it converted into 09615 which causes an error when parsing

this is the answer. From what you found, i edit the yabairc and remove window opacity values (which is 0.95 and 0.85), then activate refresh process & space with simple-bar-server, and everything work again!

**Comment by Jean-Tinland** [comment]
Oh, thanks for the input. I can't remember at all why I added this step of stripping the dots from this output.

I removed it and everything seems to still work fine.

If you pull the `master` branch of `simple-bar` the issue should be resolved.

Please let me know if this helps you and thanks again for looking into this.

**Comment by minhttx** [comment]
> Oh, thanks for the input. I can't remember at all why I added this step of stripping the dots from this output.
> 
> I removed it and everything seems to still work fine.
> 
> If you pull the `master` branch of `simple-bar` the issue should be resolved.
> 
> Please let me know if this helps you and thanks again for looking into this.

thank you! i confirm the issue is fixed. everything's ok now.

**Comment by minhttx** [comment]
alright let's close the topic
