### ISSUE TITLE
node v22 Unexpected identifier assert

### ISSUE THREAD

**Issue by alexandrelarouche** [Jean-Tinland/simple-bar-server#4]
Hi,

I rencently updated node (apparently) and noticed that simple-bar-server was not working anymore. After debugging, I noticed that `npm run dev` gave me the following error:

```
> simple-bar-server@1.0.0 dev
> node --watch index.js

file:///Users/quoding/bin/simple-bar-server/index.js:4
import config from "./config.json" assert { type: "json" };
                                   ^^^^^^

SyntaxError: Unexpected identifier 'assert'
    at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:163:18)
    at callTranslator (node:internal/modules/esm/loader:430:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:436:30)
    at async ModuleJob._link (node:internal/modules/esm/module_job:106:19)

Node.js v22.2.0
Failed running 'index.js'
```

It seems that node v22.2.0 (and probably 22.0.0) does not support the assert statement during the import. It might be good to either update the requirements for the project or rewrite an equivalent assertion statement elsewhere in index.js. The new keyword for node 22 seems to be "with" instead of assert.

I see two possibilities from here:
1) Limit the project to versions >= 18.x.x, < 22.x.x
2) Limit the projects to versions >= 22.x.x

I think option 2 might be more future-proof, but I am no veteran webdev/JS programmer.

I will push a commit and make a PR for option 2 today. I will let you decide what is best for your project!

Best,
Quoding

**Comment by Jean-Tinland** [comment]
Hi!

Thanks for the issue and the pull request!

I just pushed a fix that should resolve the issue without forcing the user to switch to the latest node version: the config file is now a `.js` so I can import it without assert its type.
