### ISSUE TITLE
Ability to get current widget (toggled) status

### ISSUE THREAD

**Issue by midfm** [Jean-Tinland/simple-bar-server#7]
Hi, 

I'd like to be able to toggle widgets automatically, based on certain events (network changes / headphones connected, etc.) but in order to do that properly, I need to know the widget's _current_ toggled on/off state (if already toggled on, leave it on, etc.).

If not would you consider something along the lines of an action like 'status' that returns a value in the http response indicating whether a widget is currently toggled on or off?

Apologies if I've missed an existing way to do get that info - I'd love to know what others are doing.

Thanks!

**Comment by Jean-Tinland** [comment]
Hi!

I won't be able to add an endpoint allowing to retrieve the current status (`on` or `off`) of a specific widget as communication through web socket is only working in one direction.

I can instead add two new endpoints: `enable` and `disable`. These endpoint will allow you to ask for the activation or deactivation of a widget and will be ignored if the specific widget is already in the desired state.

Would it be okay for you?

**Comment by midfm** [comment]
Ah, yes, clever alternative - I think that would work well for what I had in mind!

**Comment by Jean-Tinland** [comment]
This change is now implemented! I updated both `simple-bar` and `simple-bar-server`.

I also updated the [readme file](https://github.com/Jean-Tinland/simple-bar-server?tab=readme-ov-file#widgets) of this repo in order to reflect the new feature.

Yon can now enable or disable widget on the fly:

```shell
# Hide cpu widget
curl http://localhost:7776/widget/cpu/disable

# Show cpu widget
curl http://localhost:7776/widget/cpu/enable
```

Let me know if you encounter any problem with theses additions.

Thank you for the suggestion!

**Comment by midfm** [comment]
This works _really_ well, thank you so much - and for implementing it so quickly too!

Closing the issue! :)
